name: Deploy to Lambda
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:

    name: Build and Deploy Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./Spotify-Fam-Reminder-Lambda.zip ./
      
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.0.4
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1
          function_name: Spotify-Fam-Reminder-Lambda
          zip_file: Spotify-Fam-Reminder-Lambda.zip


